/**
 * Nom de pays anglais (tel que publié par Leaguepedia) → code ISO2 (le format
 * de `Player.nationality` / `Team.location`, attendu par les drapeaux du
 * front). Couvre les nationalités courantes de l'esport ; null si inconnu —
 * le fallback Pandascore comblera à l'adoption.
 */
const COUNTRY_ISO2: Record<string, string> = {
  'south korea': 'KR',
  china: 'CN',
  taiwan: 'TW',
  'hong kong': 'HK',
  macau: 'MO',
  japan: 'JP',
  vietnam: 'VN',
  thailand: 'TH',
  philippines: 'PH',
  indonesia: 'ID',
  malaysia: 'MY',
  singapore: 'SG',
  india: 'IN',
  australia: 'AU',
  'new zealand': 'NZ',
  'united states': 'US',
  canada: 'CA',
  mexico: 'MX',
  brazil: 'BR',
  argentina: 'AR',
  chile: 'CL',
  peru: 'PE',
  colombia: 'CO',
  uruguay: 'UY',
  france: 'FR',
  belgium: 'BE',
  switzerland: 'CH',
  germany: 'DE',
  austria: 'AT',
  netherlands: 'NL',
  luxembourg: 'LU',
  'united kingdom': 'GB',
  ireland: 'IE',
  spain: 'ES',
  portugal: 'PT',
  italy: 'IT',
  greece: 'GR',
  turkey: 'TR',
  poland: 'PL',
  'czech republic': 'CZ',
  czechia: 'CZ',
  slovakia: 'SK',
  hungary: 'HU',
  romania: 'RO',
  bulgaria: 'BG',
  slovenia: 'SI',
  croatia: 'HR',
  serbia: 'RS',
  'bosnia and herzegovina': 'BA',
  'north macedonia': 'MK',
  albania: 'AL',
  denmark: 'DK',
  sweden: 'SE',
  norway: 'NO',
  finland: 'FI',
  iceland: 'IS',
  estonia: 'EE',
  latvia: 'LV',
  lithuania: 'LT',
  russia: 'RU',
  ukraine: 'UA',
  belarus: 'BY',
  moldova: 'MD',
  georgia: 'GE',
  armenia: 'AM',
  azerbaijan: 'AZ',
  kazakhstan: 'KZ',
  uzbekistan: 'UZ',
  kyrgyzstan: 'KG',
  mongolia: 'MN',
  israel: 'IL',
  'saudi arabia': 'SA',
  'united arab emirates': 'AE',
  qatar: 'QA',
  kuwait: 'KW',
  bahrain: 'BH',
  jordan: 'JO',
  lebanon: 'LB',
  egypt: 'EG',
  morocco: 'MA',
  algeria: 'DZ',
  tunisia: 'TN',
  'south africa': 'ZA',
};

/** Code ISO2 d'un nom de pays anglais, null si inconnu. */
export function countryToIso2(name: string | null | undefined): string | null {
  const key = (name ?? '').trim().toLowerCase();
  if (!key) return null;
  return COUNTRY_ISO2[key] ?? null;
}
